### ISSUE TITLE
Unrecognized arguments

### ISSUE THREAD

**Issue by yash2code** [Lazza/RecuperaBit#16]
https://askubuntu.com/questions/942710/unrecognizing-arguments-recuperabit?noredirect=1

**Comment by Lazza** [comment]
This is not a bug. Assuming you have symlinked the executable to `rb` (bad choice since it will break Ruby), you have to pass a single file which is the bitstream image or the block device.

For some reason you are passing a Python file and an additional directory, thus understandably the arguments cannot be interpreted.
