### ISSUE TITLE
File Metadata - creation date

### ISSUE THREAD

**Issue by nammajamma** [Lazza/RecuperaBit#21]
Hi,

First, thank you, this is a great tool.  The ability to restore filenames and directories really helps in tracking down lost data.  This may be more of an enhancement request, but I think the ability to restore the original file's creation/modification date would further assist in investigations.

**Comment by Lazza** [comment]
> the ability to restore the original file's creation/modification date would further assist in investigations

RecuperaBit produces both CSV and [body file](http://wiki.sleuthkit.org/index.php?title=Body_file) output that can be used to generate timelines. Moreover, it is not really possible to reliably re-assign MAC times to the files because [there is no simple way to assign the creation time](https://stackoverflow.com/questions/887557/change-file-creation-date) (which is not stored on several kinds of Linux systems).

Changing the modification time could be useful in some cases, but it is not planned for now.
