### ISSUE TITLE
What are _recuperabit_content files?

### ISSUE THREAD

**Issue by slhck** [Lazza/RecuperaBit#33]
Thanks for the very useful program!

I just a have a minor support question, related to the recovered files. I'm getting a few files whose recovered path is, for example:

```
./Bilder/DSC_0016.JPG_recuperabit_content
```

These files actually are shown in my Mac's Finder as follows:

```
DSC_0016.JPG/
    DSC_0016.JPG_recuperabit_content
```

That is, a folder called like the file, and the actual file inside with the content suffix. I can rename the file from `DSC_0016.JPG_recuperabit_content` to `DSC_0016.JPG` and move it up one folder, then everything looks fine, and the image is viewable.

Is that something the program cannot auto-detect for some reason?

(It's not an issue for me to go through these files manually; I'm mostly curious!)

**Comment by Lazza** [comment]
Regarding your picture, a node is marked as directory if any of these two conditions are met:

- the MFT entry of the element is marked as directory
- there are other elements that have the id of the node as the parent (because maybe in the past the same id was used by a directory and not by a file)

This is a side effect of the reconstruction approach that you can see in [my thesis](https://www.scribd.com/doc/309337813/RecuperaBit-Forensic-File-System-Reconstruction-Given-Partially-Corrupted-Metadata) on pages 39-40 (they are 53-54 of the PDF file) if you are interested. 😃 

However, there can be inconsistencies where a file is marked as a directory, for whatever reason or somebody intentionally hid a `$DATA` attribute in a directory. You do not want to miss those contents, so RecuperaBit extracts them.

**Comment by slhck** [comment]
Gotcha, thanks! I should have mentioned that this came from a hard drive that suffered some damage, which I `ddrescued` into an image. I'm seeing some files that were recovered into the wrong folders as well, which I somewhat expected.

Perhaps it would make sense to note this in your `README` or documentation: Apparently if you rename `_recuperabit_content` files, they all (or mostly?) contain valid data.

**Comment by Lazza** [comment]
> Apparently if you rename `_recuperabit_content` files, they all (or mostly?) contain valid data.

That's the content of some file, so it will usually be "valid" for some definition of this word. 😃 Given that there are some operating systems that care about file extensions, it might be a nice idea to put the `_recuperabit_content` part at the start rather than at the end. I might consider this.

Regarding the README, I agree it is not covering 100% of RecuperaBit (only the most essential parts) and it might need some refreshment. You may consider opening a separate issue for that. 👍
