### ISSUE TITLE
Video file that was recovered will not open.

### ISSUE THREAD

**Issue by SomberFox** [Lazza/RecuperaBit#45]
Okay so I'm trying to recover files from a Windows 10 partition on a 1TB WD blue hard drive. After running the command "recuperabit /dev/sdb3 -o Recovery -s Windows10.save" it asks me to proceed so I say yes, and it begins the scanning process but then after sometime of scanning, it seems like it all just comes to a halt and never continues. It doesn’t prompt me to enter another command, the scan just stops with no prompt. If I do try to enter another command like "recover", nothing happens. Please help me figure out what to do. I absolutely need to recover some files.

**Comment by Lazza** [comment]
Are you sure it is done scanning and not just going through the areas where there is no file record, so it doesn't print any more lines because there aren't?

How many minutes did you spend scanning? 1 TB takes a while.

Anyways, you should be able to interrupt the process via the usual Ctrl+C although I would not recommend doing that because partial results could lead to less recovered files.

**Comment by SomberFox** [comment]
Okay. You were right. It did seem to finish scanning after I dozed off on the couch and waking up to it being finished. I'll change the title as I do have a new problem.

So I entered the recoverable command at the prompt and it showed me a large list. The partition I was sure I wanted to recover was 0. So following the instructions I found written in an article on your program I typed in "restore 0 5" hit enter and it proceeded to recover my files. Which is amazing. Before when I did a deep search with testdisk, it found the overwritten partition but it told me it was damaged and so I couldn't extract/copy any files from it.

But having found your program has allowed me to recover them. You are an amazing man for developing such software.

I want to make a note of something in case it has anything to do with my problem. I didn't have enough space on my other hard drive to recover all the files so the recovery process stopped sooner than it should have saying there was not enough storage space. I looked inside the destination folder to see which files I recovered. There were some video files that I really needed which I got back in seemlingly working condition. I copied them over to a USB drive and put it on a friend's windows computer to see if I could open the video files from there. I managed to open the one of the important ones(The most important) which is 2.14 GB in size. But another that is 2.70 GB in size doesn't seem to play in either VLC media player or Windows Media Player. When I try to play it with WMP, it gives me a message "Windows Media Player cannot play the file. The Player might not support the file type or might not support the codec that was used to compress the file."

**Comment by SomberFox** [comment]
Okay. I have an update and I need some help as I've tried troubleshooting a ton already myself.

It seems Recuperabit can't recover .mov files properly. My MP4 files were recovered and play fine. I tried all possible codecs to allow media players open and play the file, I've tried many media players namely Windows Media Player and VLC but I tried downloading a few others in hopes they could play it.

I then looked into .mov file repair software. I've tried at the very least, a dozen, none have worked. I've opened the file with a hex editor to find only 0s flooding the lines. This means there's no video content. Despite that, I'm still trying to convert the .mov file into a MP4 file(Still in the process of doing it). If that doesn't work either. Then would it be possible somehow to get recuperabit to recover .mov files without corrupting them in such a way?

**Comment by Lazza** [comment]
> I didn't have enough space on my other hard drive to recover all the files

OK, then you might want to consider recovering only a few directories instead of recovering the root of the drive.

> but I'm almost sure that it wasn't compressed

We are talking about NTFS compression here, not the user intentionally putting the video in a compressed archive. Files might be compressed by the OS without the user noticing. 😉 

> It seems Recuperabit can't recover .mov files properly.

This is not correct. RecuperaBit knows _nothing_ about any kind of file, it just reads the file system structure and relies on it to recover the files. 😅 If the file system is damaged some file entries might contain bogus data so the file contents cannot be recovered. It seems you encountered a few of those cases.

> I've opened the file with a hex editor to find only 0s flooding the lines. Despite that, I'm still trying to convert the .mov file into a MP4 file

You won't be able to "convert" these files as there is literally no information in them.

> Then would it be possible somehow to get recuperabit to recover .mov files without corrupting them in such a way

RecuperaBit does not corrupt anything, unfortunately you are just having bad luck because the master file table is damaged.
