### ISSUE TITLE
Maintainance

### ISSUE THREAD

**Issue by NicolasCARPi** [Lazza/RecuperaBit#59]
Hello,

As I said before, this piece of software is great and very useful to me and my collaborators.

I would like to ask @Lazza if you plan on continuing working on this (for instance making it work with python3).

I'd be willing to sponsor this work through Liberapay ;)

**Comment by Lazza** [comment]
> this piece of software is great and very useful to me and my collaborators

Thank you. 😄 

> if you plan on continuing working on this (for instance making it work with python3).

It is indeed planned. Not only a migration to Python 3 but also a rewrite of the TUI and the savefile / database structure. However, please note that currently I cannot commit to specific release dates or timetables because work-related paid gigs take up most of my time.

Starting to accept regular donations without being able to provide value for them would not be very responsible from my side. 😬

**Comment by NicolasCARPi** [comment]
>  Not only a migration to Python 3 

Well, I just pushed a commit that make the code run with python3. I still need to test it with real data but if the tests are successful I'll submit a PR :) This seems to be the right first step before any more changes.

See commit: https://github.com/deltablot/RecuperaBit/commit/3056a627811a992656d74b190de00a6308e7aba4

As you can see I commented out the reload(sys) and utf8 stuff as that poses more issues than it solves in python3.

Also did `chmod -x` the __init__.py file (btw why does it contains `from . import *`??).
