### ISSUE TITLE
The README file is not clear about using RecuperaBit on block devices directly

### ISSUE THREAD

**Issue by jadenPete** [Lazza/RecuperaBit#7]
I have an NTFS partition that got screwed up through `chkdsk` and `ntfsfix`, but any partition is too small to store an IMG. Why can't I refer to `/dev/sda4`? What could happen?

**Comment by Lazza** [comment]
I have changed the title to underline what your question implied, i.e. that the README is not very clear about this point. You are right, thanks for pointing it out. 👍 

Regarding your question, let's focus on the previous sentence written there:

> RecuperaBit does not modify the disk image, however **it does read some parts of it multiple times** through the execution.

Now, this is not an issue for a disk in good shape. However, **performing many read operations can be detrimental for damaged disks.**

This is why I do not advise using RecuperaBit on damaged drives directly. It's not meant for this purpose and it doesn't do anything to minimize the physical damage that might be caused by several read operations.

Also, I should mention that if RecuperaBit encounters an I/O error _it will simply crash._ Instead, if you clone the drive with `ddrescue` you can get a file that "masks" all I/O errors with zeros.

If the SMART data show that the drive is OK, you can run RecuperaBit on it directly.

**Comment by jadenPete** [comment]
OK, thank you.

**Comment by Boulder08** [comment]
For us Linux newbies, it could be useful to add to the readme file that you need to use sudo to run the program if the source is a block device instead of an image. It was not clear to me as the error message says that the image file cannot be found if you try to use non-elevated privileges.

**Comment by Lazza** [comment]
> it could be useful to add to the readme file that you need to use sudo (at least in Ubuntu) to run the program if the source is a block device instead of an image

Technically speaking, the README should be used to describe how the program works, not how the OS works. Permissions are a matter of how the OS is configured and what user is running the program.

Moreover, given the fact that RecuperaBit is a forensic tool *and* running it on block devices is explicitly discouraged, I would expect that Linux newbies refrain from doing it. 😅

**Comment by Boulder08** [comment]
> I would expect that Linux newbies refrain from doing it.

Hehe, fair enough :) I was just a bit confused that reading an image works but /dev/sdj gave me a strange error. In my case, Win10 just destroyed the MFT of two NTFS partitions so I knew that I could use the device directly safely (not a total computer newbie, just a Linux one :))

**Comment by Lazza** [comment]
> Win10 just destroyed the MFT of two NTFS partitions

Ah, not really a nice behavior. 😮
