### ISSUE TITLE
restore everything possible?

### ISSUE THREAD

**Issue by toneman77** [Lazza/RecuperaBit#8]
I am trying to recover a severly damaged NTFS disk and created an image with ddrescue. I first started an attempt with photorec/testdisk and that showed me 4 partitions (. After that I tried recuperabit and after the initial scanning thousands of partitions are shown after typing recoverable. I tried `restore 0 5` and 0 -1 as shown in the docs and luckily correct filenames were reconstructed. Now to do that for all those thousands of "partition" would be rather tedious, so my question is: is it possible to just say: recover anything like `restore *` ?

**Comment by Lazza** [comment]
You could tweak the script to iterate over the partitions quite easily, but you should think about whether you really want that. Most of the results will be leftover information from previous defrag operations, probably not leading to any useful recovery anyway.

To be honest, they should show after typing `allparts`, not `recoverable` because it's unlikely many of them can be recovered.

Anyway, how many of those partitions actually show that they have a significant amount of files?

See also #6.

**Comment by toneman77** [comment]
Erm... which script are you referring to?
Well I tried the first 5 and all of them had a dozen or more files and folders in it.

**Comment by Lazza** [comment]
The commands are in `main.py`, currently the `restore` command is on line 166:

https://github.com/Lazza/RecuperaBit/blob/master/main.py#L166

You could copy its definition and tweak it to do `for part in parts:` instead of relying on the user to give you a specific partition id.

But, as I said before, you should first analyze the output you got and determine if you are really interested in all those partitions. Most likely 99% of them are useless remnants and you will need to recover 2 or 3 of them.

**Comment by Lazza** [comment]
As a simple workaround you might actually invoke the `restore` command on each part by adding this piece of code:

```
    elif cmd == 'restoreall':
        if len(arguments) != 1:
            print 'Wrong number of parameters'
        else:
            for i, _ in shorthands:
                interpret('restore', [i, arguments[0]], parts, shorthands, outdir)
```

And then run:

```
restoreall 5
restoreall -1
```

However, as said before, this does not seem a good idea because you cannot really have much control on how much space you are going to write or what you are going to recover if you do not specify the root directory.

You should instead focus on evaluating which detected partitions actually hold useful data.

**Comment by toneman77** [comment]
Well. Easier said than done. I tried your new code but it failed on a file that was interpreted as a folder. Then I tried to write a 'csvall' cmd to get an overview which partitions I need (but my python-fu is very limited...) Thanks for your time.

**Comment by Lazza** [comment]
> it failed on a file that was interpreted as a folder

If you mean that it crashed then please open a new bug and include the complete crash message, because I need to see it in order to understand what the problem is.

> to get an overview which partitions I need

In most cases when one gets a lot of partitions, a lot of them seem quite empty (for instance they show 1 or 10 files when checking the `recoverable` list) and then a few of them show a very large number of files.

**Comment by toneman77** [comment]
> If you mean that it crashed then please open a new bug and include the complete crash message, because I need to see it in order to understand what the problem is. If I fix the crash, then you can use the code above. ￼

Well I killed my local branch and inserted your code again and, I must have mistyped sth the first time, because it ran through.

> In most cases when one gets a lot of partitions, a lot of them seem quite empty (for instance they show 1 or 10 files when checking the recoverable list) and then a few of them show a very large number of files.

'recoverable' showed my 71 partitions with 100-999 files and 35 with 1000-9999 files and 5 with over 10000 (those are together almost 500k files)

Anyways. It worked and I'll now work through those folders. Thank you a lot for your help.
If you, one day, consider implementing this `restoreall` option, a single folder for all partitions could be nice.
Thanks, you were a great help.

**Comment by Lazza** [comment]
> a single folder for all partitions could be nice

Even assuming file identifiers don't clash between partitions (which is very unlikely), merging all the things together would nullify the whole point of the partition detection algorithm.
